version: '3'
services:
  nodejs-server:
    build:
      context: ./SalesOrderService
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui:
    build:
      context: ./ClientService
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - ./app-ui:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules